apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service-container
          image: enamifatimazahrae2001/notification-service:latest
          ports:
            - containerPort: 9091

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9091
