apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: discoveryserver
  template:
    metadata:
      labels:
        app: discoveryserver
    spec:
      containers:
        - name: discoveryserver-container
          image: enamifatimazahrae2001/discoveryserver:latest
          ports:
            - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: discoveryserver-service
spec:
  selector:
    app: discoveryserver
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8761


